### ISSUE TITLE
Issues with Play Game Services

### ISSUE THREAD

**Issue by nosf009** [unity-plugins/Firebase-Admob-Unity#1]
Hi all;

to my knowledge either Play Game Services for Unity is not yet OK for usage with this or I simply went mad. Last 8 hours I'm trying to get pass DEX error upon build, and  I had no luck, no matter what I do - best case is - it builds but cannot show ads. 

AndroidManifest is OK, can be merged/set up.
But JAR files from this package clearly conflict with latest Play Game Services's JAR's and it's a mess.
If you use https://github.com/playgameservices/play-games-plugin-for-unity - you can clearly see that ads JAR is 8.4.0 and not 9.4.0 like rest of package, and in this case even if you build successfully - app closes with crash.

Also, Analytics won't work without Play Game Services (also Push etc), so right now I have games pending updates and have no other services than ads. 

I never did JAVA so I have no clue about it.

Anyone encountered or solved this issue? 
How would one make this work with Google Play Services for Unity?
Thanks in advance

**Comment by unity-plugins** [comment]
I am try to fix it

**Comment by nosf009** [comment]
Hey, thanks!

I believe it should maybe use GPGS 9.00 or so, but like I said - JAVA gets me very off track, I've never done it, so not sure about dependencies and classes. If you need any help with test or similar, let me know.

**Comment by Austin47** [comment]
I'm Having the same exact problem, please let me know when it's fixed or if there's any progress, thanks

**Comment by unity-plugins** [comment]
this merged google admob ,firebase analytic,google play game https://github.com/unity-plugins/google-play-game-service-unity-plugin
