### ISSUE TITLE
Banner Ad placement is off

### ISSUE THREAD

**Issue by maxxrafen** [unity-plugins/Firebase-Admob-Unity#11]
When I summon the banner to the bottom middle it hovers slightly above the bottom. How can I fix this so it aligns flush with the absolute bottom of the screen when full screen is enabled?

**Comment by unity-plugins** [comment]
Admob.Instance().showBannerRelative(AdSize.Banner, AdPosition.BOTTOM_CENTER, 0); 

the third param,0 is the offset y value.you can try to set it.

**Comment by maxxrafen** [comment]
Thank you. This does indeed allow me to move the ad around freely, which is nice. However, there seems to be a limit to how far down the banner will go. Regardless of the height I set, it always floats about 50px off the bottom.

**Comment by maxxrafen** [comment]
I apologize, I was confused between this plugin and the one firebase officially recommends for some reason. Your plugin actually works as it should and aligns flush with the bottom.
