### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by muchobucho** [unity-plugins/Firebase-Admob-Unity#5]
Hi,
I'm using your plugin and I'm getting those error logs from unity when calling
Admob.Instance().loadRewardedVideo(admobVideoID);
and
Admob.Instance().isRewardedVideoReady();

errorLogs from Unity-GamePerf:

java.lang.NullPointerException
com.admob.plugin.AdmobUnityPlugin.isRewardedVideoReady(Unknown Source)
com.unity3d.player.UnityPlayer.nativeRender(Native Method)
com.unity3d.player.UnityPlayer.a(Unknown Source)
com.unity3d.player.UnityPlayer$b$1.handleMessage(Unknown Source)
android.os.Handler.dispatchMessage(Handler.java:98)
android.os.Looper.loop(Looper.java:145)
com.unity3d.player.UnityPlayer$b.run(Unknown Source)
UnityEngine.AndroidJNISafe.CheckException ()
UnityEngine.AndroidJNISafe.CallBooleanMethod (IntPtr obj, IntPtr methodID, UnityEngine.jvalue[] args)
UnityEngine.AndroidJavaObject._Call[Boolean] (System.String methodName, System.Object[] args)
UnityEngine.AndroidJavaObject.Call[Boolean] (System.String methodName, System.Object[] args)
admob.Admob.isRewardedVideoReady ()

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.runOnUiThread(java.lang.Runnable)' on a null object reference
com.admob.plugin.AdmobUnityPlugin.loadRewardedVideo(Unknown Source)
com.unity3d.player.UnityPlayer.nativeRender(Native Method)
com.unity3d.player.UnityPlayer.a(Unknown Source)
com.unity3d.player.UnityPlayer$b$1.handleMessage(Unknown Source)
android.os.Handler.dispatchMessage(Handler.java:107)
android.os.Looper.loop(Looper.java:194)
com.unity3d.player.UnityPlayer$b.run(Unknown Source)
UnityEngine.AndroidJNISafe.CheckException ()
UnityEngine.AndroidJNISafe.CallVoidMethod (IntPtr obj, IntPtr methodID, UnityEngine.jvalue[] args)
UnityEngine.AndroidJavaObject._Call (System.String methodName, System.Object[] args)
UnityEngine.AndroidJavaObject.Call (System.String methodName, System.Object[] args)
admob.Admob.loadRewardedVideo (System.String rewardedVideoID)

it shows rewarded videos on my phone though... but seems to crash on other users phones... :(

thanks!

**Comment by unity-plugins** [comment]
fixed

**Comment by muchobucho** [comment]
thanks...
but unfortunately it stil crashes when calling Admob.Instance().isRewardedVideoReady() ... :(
(I used the unity-package from the zip file)
