### ISSUE TITLE
smart banner not working on ios

### ISSUE THREAD

**Issue by muchobucho** [unity-plugins/Firebase-Admob-Unity#7]
Hello,

I'm having trouble showing smart-banners on ios... :(
normal banner and interstitial work fine though...

I get the following error message:

-------------------------
(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

[LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x174284d30 GADBannerView:0x103b070e0.width == - 1   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x174284d30 GADBannerView:0x103b070e0.width == - 1   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.

[LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x17429f810 GADBannerView:0x103b070e0.height == - 2   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x17429f810 GADBannerView:0x103b070e0.height == - 2   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.

-------------------------

and then I get this eventCallback even for test-banners:

OnBannerEvent = onAdFailedToLoad msg = defaultBanner_Request Error: No ad to show.

I'm using your latest version and I think I have added all the frameworks you mention in the readme file...

thanks...

**Comment by unity-plugins** [comment]
Thanks for your feedback

**Comment by unity-plugins** [comment]
updated
