### ISSUE TITLE
keywords

### ISSUE THREAD

**Issue by muchobucho** [unity-plugins/Firebase-Admob-Unity#8]
Hi,

is there a way to add keywords...?

just like with the java version;

AdRequest request = new AdRequest.Builder()
.setLocation(location)
.setGender(AdRequest.GENDER_MALE)
.setBirthday(new GregorianCalendar(1990, 1, 1).getTime())
.tagForChildDirectedTreatment(false)
.addKeyword("BliBlaBlub")
.addKeyword("HalliHallo")
.build();

I couldn't find anything like this with your plugin...

thanks...

**Comment by unity-plugins** [comment]
Not support current.

**Comment by unity-plugins** [comment]
Supported now
